name: weather_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  jiffy: ^6.4.2
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  geolocator: ^13.0.4
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/

        
    
    
                                      